/*
 * generated by Xtext 2.25.0
 */
package capone.ide;

import capone.CaponeDslRuntimeModule;
import capone.CaponeDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CaponeDslIdeSetup extends CaponeDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CaponeDslRuntimeModule(), new CaponeDslIdeModule()));
	}
	
}
