/*
 * generated by Xtext 2.25.0
 */
package capone.ui;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IncrementalProjectBuilder;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.NullProgressMonitor;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.validation.ValidatingEditorCallback;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CaponeDslUiModule extends AbstractCaponeDslUiModule {

	public CaponeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback() {
		return CaponeDslEditorCallback.class;
	}
	
	public static class CaponeDslEditorCallback extends ValidatingEditorCallback {		
		@Override
		public void afterSave (XtextEditor editor) {
			// rebuild after saving to remove "dirty" markers
			try {
				IProject project = editor.getResource().getProject();
				project.build(IncrementalProjectBuilder.CLEAN_BUILD, new NullProgressMonitor());
			} 
			catch (CoreException e) {}
			super.afterSave(editor);
		}
	}			
}
