/*
 * generated by Xtext 2.25.0
 */
package capone;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CaponeDslStandaloneSetup extends CaponeDslStandaloneSetupGenerated {

	public static void doSetup() {
		new CaponeDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
