<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FactoriesPL" nsURI="http://factories/product00000" nsPrefix="factories">
  <eClassifiers xsi:type="ecore:EClass" name="Factory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" eSuperTypes="#//FElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inps" upperBound="-1" eType="#//Conveyor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outs" upperBound="-1" eType="#//Conveyor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conveyor" eSuperTypes="#//FElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
