/*
 * generated by Xtext 2.32.0
 */
package capone.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCaponeDslScopeProvider extends DelegatingScopeProvider {
}
