/**
 * generated by Xtext 2.25.0
 */
package capone.formatting2;

import capone.RuleSet;
import capone.services.CaponeDslGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class CaponeDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private CaponeDslGrammarAccess _caponeDslGrammarAccess;

  protected void _format(final capone.Module module, @Extension final IFormattableDocument document) {
    document.<RuleSet>format(module.getRules());
  }

  public void format(final Object module, final IFormattableDocument document) {
    if (module instanceof XtextResource) {
      _format((XtextResource)module, document);
      return;
    } else if (module instanceof capone.Module) {
      _format((capone.Module)module, document);
      return;
    } else if (module instanceof EObject) {
      _format((EObject)module, document);
      return;
    } else if (module == null) {
      _format((Void)null, document);
      return;
    } else if (module != null) {
      _format(module, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(module, document).toString());
    }
  }
}
