/*
 * generated by Xtext 2.32.0
 */
package capone.parser.antlr;

import capone.parser.antlr.internal.InternalCaponeDslParser;
import capone.services.CaponeDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CaponeDslParser extends AbstractAntlrParser {

	@Inject
	private CaponeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCaponeDslParser createParser(XtextTokenStream stream) {
		return new InternalCaponeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}

	public CaponeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CaponeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
